title: Voeg 3D-objecten toe aan een scène
hero_image: images/banner.png
description: Voeg 3D-objecten toe aan een scène
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - 
    title: Voeg 3D-objecten toe aan een scène

