title: Add 3D Objects to a scene
hero_image: images/banner.png
description: Add 3D Objects to a scene
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Add 3D Objects to a scene

