---
title: Ajouter des objets 3D à une scène
hero_image: images/banner.png
description: Ajouter des objets 3D à une scène
version: 4
listed: false
copyedit: false
last_tested: "2021-11-04"
steps:
  - title: Ajouter des objets 3D à une scène

